on:
  schedule:
    - cron:  '30 08 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
        with:
          target_sync_branch: master
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: cloudfoundry/nginx-buildpack
          git_fetch_args: --allow-unrelated-histories
          git_pull_args: --allow-unrelated-histories
          git_email: panzer@rabobank.nl

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false

      - name: Timestamp
        run: date
