on:
  schedule:
    - cron:  '30 08 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Sync-Fork-action
        id: sync
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          upstream_repository: cloudfoundry/nginx-buildpack
          upstream_branch: master
          target_branch: master
          git_pull_args: --allow-unrelated-histories
          git_email: panzer@rabobank.nl

      - name: Timestamp
        run: date
